### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by jan-2017** [lr94/phpbb-connectionlogger#3]
i have added german translation
I hope it is inserted correctly
Bye Jan

**Comment by lr94** [comment]
Create a pull request, so I can merge your changes in the master branch. Thank you for your translation!

**Comment by jan-2017** [comment]
Oh ok, i'm sorry.
I have corrected it.

**Comment by lr94** [comment]
I merged your fork and closed the pull request. You created the file "de" in "languages", but you should have named it info_acp_lc.php and put it in a _directory_  named "de". However I corrected it :)
Once again, thank you for your translation!

**Comment by jan-2017** [comment]
Oh sorry, i´m a newbie at github. Now i´m a little bit clever again ;-) , thanks , bye Jan
