### ISSUE TITLE
Colors in acp only green

### ISSUE THREAD

**Issue by jan-2017** [lr94/phpbb-connectionlogger#4]
Hello. If the login was successful, the entry in acp will be green. If the login was unsuccessful, it will also appear in green.

In file adm/style/acp_lc_view i can read FF0000 for login failure.

Can you help me?

Bye Jan

**Comment by lr94** [comment]
...that's very strange. I just tried and I see unsuccessful login attempts correctly shown in red.
Does it appen for every failed login attempt? Both normal login and ACP ones?

**Comment by jan-2017** [comment]
Yes , both (normal and acp) are displayed in green. If i change the color in adm/style/acp_lc_view to yellow - no reactions. If I delete the german language file, then it is displayed in red. Now i check my translation again!

**Comment by lr94** [comment]
I have no idea about how the translation file could cause a similar problem, however as I wrote in the other issue ticket you opened your translation file was in the wrong place and had the wrong name. Maybe now it works.

**Comment by lr94** [comment]
Ok nervermind, I fixed the name and now I'm finally able to reproduce your issue: I can see "Falsches Passwort eingegeben" in green. I'll try to understand why this is happening

**Comment by lr94** [comment]
Ok, I fixed it by editing the language file. This should have not been necessary, but this part of the extension was not projected by me (it comes from the old PhpBB 3.0.x mod by El Globo) and when I ported it I wasn't able to change the way it stores the logs on the db without breaking backward compatibility (I had that mod on my 3.0.x board and I didn't want to lose the ability to browse my old logs when upgrading to 3.2.0).

Please download again the extension cloning the repository and tell me if it works now.

**Comment by jan-2017** [comment]
I have tested again.Extension disabled , new repository (with "de" folder from me) ,uploaded and ext. enabled again. Now i see all login failure in color red!!!!!!! Nice very thanks for fixing this little bug! Bye Jan ... Go for languagefile "german" ;-)
