### ISSUE TITLE
The remaining attempts aren´t displayed

### ISSUE THREAD

**Issue by jan-2017** [lr94/phpbb-connectionlogger#6]
Hello. Here on this side (https://camo.phpbb.com/59f4c19ae41311eed59781cdb5858a79f6e6b0a3/687474703a2f2f692e696d6775722e636f6d2f52614331346e622e706e67) i see in the screenshot that apperas "Failure - incorrect password (2 attempts)". In my acp / extensions/connetion logs i don´t see this if a users try to log in with a wrong password.

Bye Jan

**Comment by lr94** [comment]
Sorry for the late reply.

![screenshot](https://user-images.githubusercontent.com/27508788/39668147-d82d432a-50c5-11e8-9e54-c6d933e3e134.png)
I can see it correctly, though the word "attempts" hasn't been translated. Could you please provide a screenshot? Did you make other changes (besides those to the stylesheet you mentioned in the other issue)?

**Comment by jan-2017** [comment]
I don't know ... it doesn't work.
The attemps are not displayed either in english or in german language. Very strange.

**Comment by lr94** [comment]
Umh. I don't know how to reproduce your problem, so I'm unable to fix it!
(Please note that the number of attempts is shown only if there is _more than one_ consecutive failed attempt)
