### ISSUE TITLE
Log in failure text - change color

### ISSUE THREAD

**Issue by jan-2017** [lr94/phpbb-connectionlogger#7]
In the file "acp_lc_view" i added in line 10 this:

	font-size: 100%;
	padding-left: 4px;
	padding-right: 4px;
	padding-bottom: 4px;
	padding-top: 4px;
	background: #FF0000;
	color: #FFFFFF;
	border-radius: 4px 4px 4px 4px;

Now i can better recognize errors in the log. 
Bye Jan

**Comment by lr94** [comment]
Hello! I think this is nice as a customization of this extension for your own board, but personally I don't like very much that look for the "failure" log entries and I think that those entries are already enough visible, so I don't think I'm going to include this in the "official release" of this extension.
Thank you anyway :)
